version: '3'

name: recipe-microservice-auth

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      - user_db

  user_db:
    image: postgres:15-alpine3.19
    ports:
      - "${DB_PORT_DOCKER}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
