version: '3'

name: recipe-microservice-auth

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  user_db:
    image: postgres:15-alpine3.19
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
